#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# copyright (C) 1999-2006 Mitel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------
package esmith::console;

use strict;

use Locale::gettext;
use esmith::ConfigDB::unsaved;
use esmith::console;

my $console = esmith::console->new();

my $db = esmith::ConfigDB::unsaved->open;

my $termType = $db->get_prop('serial-console', 'Terminal') || '';

$ENV{TERM} = $termType if($termType);

use esmith::console::system_password;
esmith::console::system_password->new->doit($console, $db);

use esmith::console::configure;
esmith::console::configure->new(bootstrap => 1)->doit($console, $db);

use esmith::console::save_config;
esmith::console::save_config->new->doit($console, $db);

system("/usr/bin/tput", "clear");
exit (0);

