#!/bin/sh

#----------------------------------------------------------------------
# copyright (C) 1999, 2000 e-smith, inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
# Technical support for this program is available from e-smith, inc.
# Please visit our web site www.e-smith.com for details.
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# e-smith-service: meta-init script which runs the underlying service
#                  based on the name of the service script invoked.
#		   For example S85sshd would run init.d/sshd
#----------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

METASERVICE=e-smith-service
SERVICE=$( basename $0 | sed -e 's/^[SK][0-9][0-9]*//' )

export HOME="/root"

case ${SERVICE} in
    ${METASERVICE})	echo "We don't really want to exec ${METASERVICE}" 1>&2
			exit 2 
			;;
esac

S_INITSCRIPT="/etc/rc.d/init.d/supervise/${SERVICE}"
INITSCRIPT="/etc/rc.d/init.d/${SERVICE}"
if [ -f ${S_INITSCRIPT} ]
then
    # Prefer a supervise init script if we find one
    INITSCRIPT=${S_INITSCRIPT}
fi

STATUS=$( /sbin/e-smith/db configuration getprop ${SERVICE} status )

if [ "${STATUS}" != "enabled" ]
then
    case $1 in
	condrestart)
	    exit 0 ;;
	start)
	    exit 99 ;;
    esac
fi

if [ -f ${INITSCRIPT} ]
then
    if [ -x ${INITSCRIPT} ]
    then
	exec ${INITSCRIPT} $@
    else
	exec /bin/sh ${INITSCRIPT} $@
    fi
fi

echo "$0: Couldn't find/execute init script for service ${SERVICE}" 1>&2
exit 1
