#!/bin/bash
#
# NethServer runlevel connector
#
# Copyright (C) 2012 Nethesis srl
#
#
#       /etc/rc.d/init.d/nethserver-rc
#
#       NethServer runlevel connector
#       Raise events based on system runlevel
#
# chkconfig:	2345 90 10
# description:	Raise events based on system runlevel

### BEGIN INIT INFO
# Provides:		nethserver-rc
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	NethServer runlevel connector
# Description:		Raise events based on system runlevel
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

case "$1" in
    start|stop)
        /sbin/e-smith/signal-event system-$1
        ;;
    restart|reload)
	echo "$1 is not implemented"
	exit 1
        ;;
    *)
        echo "Usage: <servicename> {start|stop|status|reload|restart"
        exit 1
        ;;
esac
exit $?
