#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;


#--------------------------------------------------
# actions for network-create event
#--------------------------------------------------
event_actions('network-create', qw(
    firewall-adjust      70
));

#--------------------------------------------------
# actions for network-modify event
#--------------------------------------------------
event_actions('network-modify', qw(
    firewall-adjust      70
));

#--------------------------------------------------
# actions for network-delete event
#--------------------------------------------------
event_actions('network-delete', qw(
    firewall-adjust      70
));

#--------------------------------------------------
# actions for nethserver-base-update event
#--------------------------------------------------
event_actions('nethserver-base-update', qw(
    initialize-default-databases      00
    nethserver-base-selinux-setup     10
    remount-filesystems               10
    nethserver-base-conf              40
    nethserver-base-pam-setup         50
    nethserver-base-mail-aliases      50
));

event_templates('nethserver-base-update', qw(
    /etc/hosts
    /etc/fstab
    /etc/resolv.conf
    /etc/selinux/config
    /etc/pam.d/system-auth-nh
    /etc/pam.d/password-auth-nh
    /etc/sudoers
    /etc/shells
    /etc/rc.d/rc.local
    /etc/krb5.conf
    /etc/logviewer.conf
    /etc/logrotate.conf
));


#
# Template headers
#
		
safe_symlink(
    "/etc/e-smith/templates-default/template-begin-pam", 
    "root/etc/e-smith/templates/etc/pam.d/system-auth-nh/template-begin");		

safe_symlink(
    "/etc/e-smith/templates-default/template-begin-shell", 
    "root/etc/e-smith/templates/etc/rc.d/rc.local/template-begin");		


#--------------------------------------------------
# actions for interface-modify event #1532
#--------------------------------------------------
event_actions('interface-update', qw(
              network-stop               04
              interface-config-reset     25
              interface-config-write     30
              reset-udev-rules           35
              network-start              70
              interface-config-hostname  75
              static-routes-save         80
              firewall-adjust            90
));

event_templates('interface-update', qw(
     /etc/modprobe.d/bonding.conf
     /etc/sysconfig/network
     /etc/hosts
     /etc/resolv.conf
));


#--------------------------------------------------
# Refs #939 tcp/udp port server validator
#--------------------------------------------------
validator_actions('remote-port', qw(
		  open-tcp-connection 10
));


#--------------------------------------------------
# Refs #1038 expand /etc/hosts template on host 
# events -- FIXME: should be moved into 
# nethserver-hosts package (?)
#--------------------------------------------------
templates2events('/etc/hosts', qw(
		 host-create
		 host-delete
		 host-modify
));


#--------------------------------------------------
# empty events:
#--------------------------------------------------
foreach (qw(

)) {
    File::Path::make_path('root/etc/e-smith/events/' . $_);
}

#--------------------------------------------------
# actions for system-init event
#--------------------------------------------------
event_actions('system-init', qw(
    initialize-default-databases      00
    nethserver-base-initialize-db     50
    nethserver-generate-certificate   55
    init-repo                         60
    system-adjust                     90
    nethserver-base-interface-update  95
));

#
# certificate-update event
#
event_actions('certificate-update', qw(
    nethserver-generate-certificate 02
));

#
# profile-modify event
#
event_actions('profile-modify', qw(
    nethserver-base-mail-aliases 30
));

event_services('profile-modify', qw(
    postfix reload
));

#
# fstab-update
#
$event = "fstab-update";
event_actions($event, 'remount-filesystems' => 20);
templates2events('/etc/fstab', $event);

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-base-migrate' => 20);

#--------------------------------------------------
# actions for firewall-adjust event
#--------------------------------------------------

$event = "firewall-adjust";
event_actions($event, 'firewall-adjust' => 20);

#--------------------------------------------------
# actions for runlevel-adjust event
#--------------------------------------------------

$event = "runlevel-adjust";
event_actions($event, 'runlevel-adjust' => 20);

#--------------------------------------------------
# actions for lokkit-save event
#--------------------------------------------------

$event = "lokkit-save";
templates2events('/etc/sysconfig/system-config-firewall', $event);
templates2events('/etc/sysconfig/ipv4_services_custom', $event);
event_actions($event, 'lokkit-apply' => 20);


#
# hostname-modify event (#1878)
#
event_templates('hostname-modify', qw(
     /etc/sysconfig/network
));

event_actions('hostname-modify', qw(
     interface-config-hostname  02
     system-adjust 96
));

#
# Validator for log file names (#470)
#
validator_actions('logfile', qw(
		  logfile 10
));

#
# Validator for network configuration consistency (#2103)
# 
validator_actions('interface-config', qw(
		  interface-role 10
));

#--------------------------------------------------
# password-modify event
#--------------------------------------------------
event_actions('password-modify', qw(
              password-set 25
              password-cleanup 90
));

#--------------------------------------------------
# validate passwords
#--------------------------------------------------
validator_actions('password-strength',
                  'password-strength' => '10');


#--------------------------------------------------
# actions for static-routes-save event
#--------------------------------------------------

$event = "static-routes-save";

event_actions($event, qw(
    network-route-down          15
    interface-config-write      25
    network-route-up            35
));

exit 0;
