#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);
use File::Path;


#--------------------------------------------------
# actions for console-save event
#--------------------------------------------------
my $event = "console-save";
event_link("reset-unsavedflag", $event, "95");


#--------------------------------------------------
# actions for bootstrap-console-save event
#--------------------------------------------------
$event = "bootstrap-console-save";
event_link("reset-unsavedflag", $event, "95");


#--------------------------------------------------
# actions for network-create event
#--------------------------------------------------
event_templates('network-create',
		'/etc/localnetworks');
# event_link("conf-routes", 'network-create', "89");


#--------------------------------------------------
# actions for network-delete event
#--------------------------------------------------
event_templates('network-delete',
		'/etc/localnetworks');
# event_link("conf-routes", 'network-delete', "89");


#--------------------------------------------------
# actions for nethserver-base-update event
#--------------------------------------------------
event_actions('nethserver-base-update', 
    "initialize-default-databases"   => "00",
    "nethserver-base-selinux-setup"  => "10",
    "nethserver-base-conf"           => "40",
    "nethserver-base-pam-setup"      => "50",
    "firewall-adjust"                => "70",
    "runlevel-adjust"                => "71",
);

event_templates('nethserver-base-update', qw(
    /etc/hosts
    /etc/resolv.conf
    /etc/selinux/config
    /etc/libuser.conf
    /etc/pam.d/system-auth-nh
    /etc/pam.d/password-auth-nh
    /etc/sudoers
    /etc/sysconfig/sshd
    /etc/localnetworks
    /etc/hosts.allow
    /etc/hosts.deny
    /etc/shells
));
		
safe_symlink("/etc/e-smith/templates-default/template-begin-pam", "root/etc/e-smith/templates/etc/pam.d/system-auth-nh/template-begin");		


#--------------------------------------------------
# actions for network-update event
#--------------------------------------------------
$event = "network-update";
event_link("network-config-reset", $event, "25");
event_link("network-config-write", $event, "30");
event_link("network-config-restart", $event, "70");
event_link("network-config-hostname", $event, "75");
event_templates($event,
     '/etc/modprobe.d/bonding.conf',
     '/etc/udev/rules.d/70-persistent-net.rules',
     '/etc/sysconfig/network',
     '/etc/localnetworks',
     '/etc/hosts'
);


#--------------------------------------------------
# Refs #939 tcp/udp port server validator
#--------------------------------------------------
validator_actions('remote-port',
		  'open-tcp-connection', => '10');


#--------------------------------------------------
# nethserver-base-save event
#--------------------------------------------------
event_templates('nethserver-base-save',
		'/etc/hosts.allow',
		'/etc/hosts.deny',
		'/etc/sysconfig/sshd');

event_actions('nethserver-base-save',
	      'firewall-adjust' => '60',
	      'runlevel-adjust' => '61');

event_services('nethserver-base-save', qw(
               sshd reload
));

#--------------------------------------------------
# Refs #1038 expand /etc/hosts template on host 
# events
#--------------------------------------------------
templates2events('/etc/hosts', 
		 'host-create',
		 'host-delete',
		 'host-modify');


#--------------------------------------------------
# system-{start,stop} events
#--------------------------------------------------
File::Path::make_path('root/etc/e-smith/events/system-start',
		      'root/etc/e-smith/events/system-stop');

# Refs #1066 - The skel root directory
File::Path::make_path('root/etc/e-smith/skel');

exit 0;

