#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

event_actions('trusted-networks-modify', qw(
    firewall-adjust 94
));

#--------------------------------------------------
# actions for nethserver-base-update event
#--------------------------------------------------
event_actions('nethserver-base-update', qw(
    initialize-default-databases      00
    nethserver-base-selinux-setup     10
    home-bind                         10
    remount-filesystems               10
    nethserver-base-conf              40
    nethserver-base-mail-aliases      50
));

event_templates('nethserver-base-update', qw(
    /etc/hosts
    /etc/fstab
    /etc/resolv.conf
    /etc/selinux/config
    /etc/sudoers
    /etc/shells
    /etc/logviewer.conf
    /etc/logrotate.conf
    /etc/backup-config.d/nethserver-certificates.include
    /etc/yum.conf
));

event_services('nethserver-base-update', qw(
    systemd-udevd restart
));

#--------------------------------------------------
# actions for interface-update event #1532
#--------------------------------------------------
event_actions('interface-update', qw(
              network-stop               04
              interface-rename           20
              adjust-fixnetwork-flag     21
              interface-config-reset     25
              interface-config-write     30
              network-start              70
              static-routes-save         80
              firewall-adjust            90
              trusted-networks-modify    95
));

event_templates('interface-update', qw(
     /etc/modprobe.d/bonding.conf
     /etc/sysconfig/network
     /etc/hosts
     /etc/resolv.conf
));


#--------------------------------------------------
# Refs #939 tcp/udp port server validator
#--------------------------------------------------
validator_actions('remote-port', qw(
		  open-tcp-connection 10
));


#--------------------------------------------------
# Refs #1038 expand /etc/hosts template on host 
# events -- FIXME: should be moved into 
# nethserver-hosts package (?)
#--------------------------------------------------
templates2events('/etc/hosts', qw(
		 host-create
		 host-delete
		 host-modify
));


#--------------------------------------------------
# empty events:
#--------------------------------------------------
foreach (qw(

)) {
    File::Path::make_path('root/etc/e-smith/events/' . $_);
}

#--------------------------------------------------
# actions for system-init event
#--------------------------------------------------
event_actions('system-init', qw(
    initialize-default-databases      00
    nethserver-base-initialize-db     50
    nethserver-generate-certificate   55
    system-adjust                     90
    nethserver-base-interface-update  95
    nethserver-system-init-clear      98
));

#
# certificate-update event
#
templates2events('/etc/backup-config.d/nethserver-certificates.include', 'certificate-update');

#
# profile-modify event
#
event_actions('profile-modify', qw(
    nethserver-base-mail-aliases 30
));

event_services('profile-modify', qw(
    postfix reload
));

#
# fstab-update
#
$event = "fstab-update";
event_actions($event, 'remount-filesystems' => 20);
templates2events('/etc/fstab', $event);

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-base-migrate' => 20);

#--------------------------------------------------
# actions for firewall-adjust event
#--------------------------------------------------

$event = "firewall-adjust";
event_actions($event, 'firewall-adjust' => 20);

#--------------------------------------------------
# actions for runlevel-adjust event
#--------------------------------------------------

$event = "runlevel-adjust";
event_actions($event, 'runlevel-adjust' => 20);

#
# hostname-modify event (#1878)
#
event_templates('hostname-modify', qw(
     /etc/sysconfig/network
));

event_actions('hostname-modify', qw(
     system-adjust 96
));

#
# Validator for log file names (#470)
#
validator_actions('logfile', qw(
		  logfile 10
));

#
# Validator for network configuration consistency (#2103)
# 
validator_actions('interface-config', qw(
		  interface-role 10
));

#--------------------------------------------------
# password-modify event
#--------------------------------------------------
event_actions('password-modify', qw(
              password-set 25
              password-cleanup 90
));

#--------------------------------------------------
# validate passwords
#--------------------------------------------------
validator_actions('password-strength',
                  'password-strength' => '10');


#--------------------------------------------------
# actions for static-routes-save event
#--------------------------------------------------

$event = "static-routes-save";

event_actions($event, qw(
    network-route-down          15
    interface-config-write      25
    network-route-up            35
));

#--------------------------------------------------
# Refs #3272 uniq key networks db validator
#--------------------------------------------------
validator_actions('network-create', qw(
                  uniq-networksdb-key 20
                  ));

#
# system-shutdown event
#
event_actions('system-shutdown', qw(
    system-shutdown 20
));


#--------------------------------------------------
# actions for certificate-upload event
#--------------------------------------------------

$event = "certificate-upload";

event_actions($event, qw(
    nethserver-certificate-upload	15
));

templates2events('/etc/backup-config.d/nethserver-certificates.include', $event);

#--------------------------------------------------
# validate pem certificate
#--------------------------------------------------
validator_actions('pem-certificate',
                  'pem-certificate' => '10');

#--------------------------------------------------
# validate rsa key
#--------------------------------------------------
validator_actions('rsa-key',
                  'rsa-key' => '10');

#--------------------------------------------------
# actions for proxy-modify event
#--------------------------------------------------
event_templates('proxy-modify', qw(
    /etc/yum.conf
    /etc/profile.d/nethserver_proxy.sh
));


validator_actions('myhostname', qw(
    hostname-length 10
));

event_actions('post-restore-config', qw(
    hostname-set       01
));

