#!/usr/bin/python

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import division
from __future__ import print_function
import yum
import os
import sys
import syslog
import getopt
import nethserver.ptrack
import yum.callbacks
import yum.Errors
import yum.i18n # exception2msg
import re
import json

# If True, generate JSON output for cockpit
json_output = False

def joutput(data):
    global json_output
    if json_output:
        print(json.dumps(data))

def warning(*objs):
    print(*objs, file=sys.stderr)

class TransactionCallback( yum.callbacks.ProcessTransNoOutputCallback ):
    def __init__(self, repos, tracker_client, parent_task_id):
        self.tracker_client = tracker_client
        self.parent_task_id = parent_task_id
        self.repos = repos

    def event(self, state, data=None):
        if(state == yum.callbacks.PT_DOWNLOAD_PKGS
           and not data is None 
           and len(data) > 0):
            self.trackDownloads(data)
        if state in yum.callbacks.PT_MESSAGES:
            joutput({'event': yum.callbacks.PT_MESSAGES[state], 'state': 'running', 'steps' : -1})
            
    def trackDownloads(self, pkgs):            
        # If there is at least one download, declare Download task:
        targets = []
        for po in pkgs:
            if not hasattr(po, 'pkgtype') or po.pkgtype != 'local':
                targets.append(po)

        if targets:
            task_id = self.tracker_client.declare_task("Download", self.parent_task_id, 25.0)
            self.repos.setProgressBar(DownloadCallback(self.tracker_client, task_id, targets))


class DownloadCallback(  yum.callbacks.DownloadBaseCallback ):
    def __init__(self, tracker_client, task_id, pkgs):
        yum.callbacks.DownloadBaseCallback.__init__(self)
        if(not isinstance(tracker_client, nethserver.ptrack.TrackerClient)):
            raise Exception("Invalid nethserver.ptrack.TrackerClient instance")

        self.tracker_client = tracker_client
        self.task_id = task_id
        self.rpm_task_id = self.tracker_client.declare_task("Download RPMs", self.task_id, 2.0)
        self.drpm_task_id = None
        self.rebuild_task_id = None
        self.pkgs = pkgs
        self.pkgs_progress = 0.0

    def runWithDeltaTask(self):
        if(self.drpm_task_id):
            return

        self.drpm_task_id = self.tracker_client.declare_task("Download DRPMs", self.task_id, 2.0)
        self.rebuild_task_id = self.tracker_client.declare_task("Delta rebuilding", self.task_id, 1.0)
        
    def updateProgress(self,name,frac,fread,ftime):
        if not type(name) is str:
            return

        task_id = self.rpm_task_id
        progress = None
        message = ""

        if name.endswith('.rpm'):
            task_id = self.rpm_task_id
            try:
                if frac == 1.0:
                    self.pkgs_progress += 1.0 / len(self.pkgs)
                progress = self.pkgs_progress

            except Exception as e:
                pass
            message = '%s %s %s' % (name, fread, ftime)
        elif name.endswith('.drpm'):
            self.runWithDeltaTask()
            task_id = self.drpm_task_id
            mo = re.match('\((\d+)/(\d+)\)', name)
            try:
                progress = float(mo.group(1)) / float(mo.group(2))
            except Exception as e:
                pass
            message = '%s' % (name)
        elif name.endswith('/prestodelta'):
            self.runWithDeltaTask()
            task_id = self.drpm_task_id
            progress = 0.01
            message = 'Fetching prestodelta'
        elif name == '<delta rebuild>':
            self.runWithDeltaTask()
            task_id = self.rebuild_task_id
            progress = frac
            message = "%s %s" % (fread, ftime)

        if(not progress is None):
            self.tracker_client.set_task_progress(task_id, progress, message)

        joutput({'event': 'Downloading - %s' % name, 'state': 'running', 'steps': -1})

class TrackerClientCallBack(yum.rpmtrans.RPMBaseCallback):
    def __init__(self, tracker_client, parent_task_id):
        yum.rpmtrans.RPMBaseCallback.__init__(self)
        if(not isinstance(tracker_client, nethserver.ptrack.TrackerClient)):
            raise Exception("Invalid nethserver.ptrack.TrackerClient instance")
        self.tracker_client = tracker_client
        self.task_id = tracker_client.declare_task("RPM transaction", parent_task_id, 25.0)

    def _get_action_name(self, action):
        if action in yum.TS_INSTALL_STATES:
            return 'Installing'
        elif action in yum.TS_REMOVE_STATES:
            return 'Removing'
        else:
            return ''

    def event(self, package, action, te_current, te_total, ts_current, ts_total):
        # Element progress
        c = float(te_current) / float(te_total)
        # Transaction progress
        p = min(1.0, (float(ts_current) - 1.0 + c) / float(ts_total))
        message = "%s %s" % (package, self._get_action_name(action))
        self.tracker_client.set_task_progress(self.task_id, p, message)
        joutput({'event': "%s %s" % (self._get_action_name(action), package), 'state': 'running', 'steps': -1})

def usage():
    warning("Usage: %s {<command> {PACKAGE|@GROUP}}..." % sys.argv[0])
    warning("    command: [--install|--update|--strict-update|--remove] [--json]")
    sys.exit(1)

def main():
    global json_output

    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['install=','strict-update=','update=','remove=','json'])
    except getopt.GetoptError as err:
        usage()

    if(len(args) > 0 or len(opts) == 0):
        usage()
            
    actions = {'install': [], 'update': [], 'strict-update': [], 'remove': []}
    tracker_client = None
    exitcode = 0
    strict = False

    if opts[0][0] == '--strict-update':
       opts[0] = ('--update',opts[0][1]) # map to correct yum action
       strict = True

    for key, val in opts:
        if key == '--json':
            json_output = True
        else:
            map(lambda x: actions[key[2:]].append(x), val.split(','))

    syslog.openlog('pkgaction',syslog.LOG_PID);
    tracker_client = nethserver.ptrack.TrackerClient()

    current_task_id = 0

    try:

        ypbc = yum._YumPreBaseConf()
        ypbc.debuglevel = -1
        ypbc.errorlevel = -1
        yb = yum.YumBase()
        yb.preconf = ypbc
        yb.conf.assumeyes = 1
        if strict:
            yb.conf.reposdir = '/etc/nethserver/yum-update.d/'

        joutput({'event': 'Initialization', 'state': 'running', 'steps': -1})
        task_dep_id = tracker_client.declare_task("Initialization", 0, 4.0)
        task_chn_id = tracker_client.declare_task("Applying changes", 0, 96.0)
        task_sys_id = tracker_client.declare_task("System configuration", task_chn_id, 50.0)
        os.environ["PTRACK_TASKID"] = str(task_sys_id)

        current_task_id = task_dep_id

        tracker_client.set_task_progress(task_dep_id, 0.01)

        for action in ['remove', 'update', 'install']:
            syslog.syslog("%s: %s" % (action, ', '.join(actions[action])))
            for pkg in actions[action]:
                getattr(yb, action)(pattern=pkg)

        tracker_client.set_task_progress(task_dep_id, 0.5, 'Resolving RPM dependencies')
        joutput({'event': 'Resolving RPM dependencies', 'state': 'running', 'steps': -1})
        yb.resolveDeps()
        tracker_client.set_task_done(task_dep_id)

        current_task_id = task_chn_id

        yb._limit_installonly_pkgs()
        yb.processTransaction(
            callback   = TransactionCallback(yb.repos, tracker_client, task_chn_id),
            rpmDisplay = TrackerClientCallBack(tracker_client, task_chn_id)
        )
        
        current_task_id = task_sys_id

        exitcode = 0 if getattr(yb, 'nethserver_events', True) else 2

        if(exitcode == 0):
            tracker_client.set_task_done(task_sys_id)
            tracker_client.set_task_done(task_chn_id)
        else:
            # errors from events: set error state on both the parent
            # and its child.
            tracker_client.set_task_done(task_sys_id, '', exitcode)
            tracker_client.set_task_done(task_chn_id, '', exitcode)

    except Exception as e:
        try:
            message = "[%s] %s" % (e.__class__.__name__, yum.i18n.exception2msg(e))
        except:
            message = "[%s] %s" % (e.__class__.__name__, e)

        tracker_client.set_task_done(current_task_id, message, 1)
        if json_output:
            joutput({'event': None, 'message': message, 'status': 'failed', 'steps': -1})
        else:
            warning(message)
        syslog.syslog(syslog.LOG_ERR, message)
        sys.exit(1)
    
    joutput({'event': 'Transaction end', 'status': 'success', 'steps' : -1})
    sys.exit(exitcode);

if __name__ == "__main__":
    main()
