#!/bin/bash

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

DEFAULT_KEY="/etc/pki/tls/private/NSRV.key"
PRIVATE_KEY=${1:-$DEFAULT_KEY}

if [ -f ${PRIVATE_KEY} ]; then
    # Fail, refusing to overwrite existing PRIVATE_KEY file.
    echo "$0: file ${PRIVATE_KEY} exists!" 1>&2
    exit 1
fi

# Generate a private RSA key
umask 077
/usr/bin/openssl genpkey -out "${PRIVATE_KEY}" -algorithm RSA >/dev/null 2>&1
