#!/bin/bash -x

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

spoolfile=$1

if [ ! -r "${spoolfile}" ]; then
    echo $(basename $0) "[ERROR] missing file argument!";
    exit 1;
fi

exec <${spoolfile}

declare -a argv

while read -a argv; do
    /sbin/e-smith/signal-event ${argv[*]}
done

rm -f ${spoolfile}
