#!/bin/sh

for card in `ls /sys/class/net`; do

	#Check if this is an Ethernet device (type=1)
	if [ `cat /sys/class/net/$card/type` == "1" ]; then
		hwaddr=`cat /sys/class/net/$card/address`

		#Check that is no VLAN if
		if [[ ! "$card" =~ "[.]" ]]; then

			#check if this not a bridge
			if [ ! -e /sys/class/net/$card/brforward ]; then

				#Check if mac is valid (not 00:00... or FF:FF...)
				if [ ! "$hwaddr" == "00:00:00:00:00:00" ];then
				if [ ! "$hwaddr" == "ff:ff:ff:ff:ff:ff" ];then

					driver=`basename $(ls -l /sys/class/net/$card/device/driver | awk '{print$NF}' )`
					type=`basename $(ls -l /sys/class/net/$card/device/subsystem | awk '{print$NF}' )`

					#Default if not avaiable in /sys/class/net
					if [ "a$type" == "a" ]; then
						type="???"
					fi
					if [ "a$driver" == "a" ]; then
						driver="Unknown Network Interface ($card)"
					fi
                                        curr=`/sbin/e-smith/db networks get $card`
					if [ "x$curr" == "x" ]; then
						# add to networks db
						/sbin/e-smith/db networks set $card ethernet hwaddr $hwaddr 
						/sbin/e-smith/db networks setprop $card role '' 
					fi   
				fi
				fi
			fi
		fi
	fi
done

exit 0
