#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Automatically switch to NsReleaseLock if CentOS and NethServer
# have different releases.
#

. /etc/os-release

systemid=$(/sbin/e-smith/config getprop subscription SystemId)
lock=$(/sbin/e-smith/config getprop sysconfig NsReleaseLock)

if [ -n "$systemid" ]; then
    exit 0
fi

ce_release=$(curl -s "http://mirrorlist.centos.org/?release=$VERSION_ID&arch=x86_64&repo=updates&infra=stock" | head -n 1 | grep -o -E "$VERSION_ID\.[0-9]\.[0-9]+")
ns_release=$(curl -s "http://mirrorlist.nethserver.org/?release=$VERSION_ID&repo=updates&arch=x86_64" | head -n 1 | grep -o -E "$VERSION_ID\.[0-9]\.[0-9]+")

if [ -n "$ce_release" ] && [ -n "$ns_release" ] && [ "$ce_release" != "$ns_release" ] && [ $lock != "enabled" ]; then
    echo "CentOS and NethServer releases are different!"
    echo
    echo -e "CentOS:     $ce_release"
    echo -e "NethServer: $ns_release"
    /sbin/e-smith/config setprop sysconfig NsReleaseLock enabled
    /sbin/e-smith/signal-event software-repos-save
    echo
    echo "NsReleaseLock is now enabled."
fi
