#!/bin/bash
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Run nethserver-check-certificate action with special event name
# "checkgen" and compare command exit code value.
/etc/e-smith/events/actions/nethserver-base-check-certificate checkgen

# The 6 value indicates a new certificate has been released: notify
# daemons.
if [ $? -eq 6 ]; then
   [ -d /etc/e-smith/events/certificate-update ] && \
       /sbin/e-smith/signal-event certificate-update
fi

