#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Configuration 
# description : Review configuration
# navigation  : 6000 6800
#----------------------------------------------------------------------
#----------------------------------------------------------------------
# copyright (C) 2002 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------



use strict;
use esmith::FormMagick::Panel::review;
my $f = esmith::FormMagick::Panel::review->new();
$f->display();




=head1 TESTING


=begin testing

use esmith::FormMagick::Tester;
use esmith::TestUtils;
use esmith::ConfigDB;

my $panel = 'review';
my $panel_path = "/etc/e-smith/web/functions/".$panel;
my $ua = esmith::FormMagick::Tester->new();


is  (mode($panel_path), '4750',              "Check permissions on script");
my @stat = stat($panel_path);
is  (getpwuid($stat[4]), 'root', "File is owned by root");
is  (getgrgid($stat[5]), 'admin', "File is owned by group admin");
ok  ($ua->get_panel($panel),            "ABOUT TO RUN L10N TESTS");
is  ($ua->{status}, 200,                "200 OK");
ok  ($ua->set_language("en"),           "Set language to English");
ok  ($ua->get_panel($panel),            "Get panel");
is  ($ua->{status}, 200,                "200 OK");
like($ua->{content}, qr/Review configuration/, "Saw translated form title");
like($ua->{content}, qr/Email Addresses/, "Saw email addresses");

=end testing

=cut

__DATA__
<form title="Review configuration" header="/etc/e-smith/web/common/head.tmpl" footer="/etc/e-smith/web/common/foot.tmpl">
    <page name="First"  post-event="change_settings()" pre-event="turn_off_buttons()">
      <description>DESCRIPTION</description>

	<subroutine src="print_page()"/>
  </page>  

</form>
