#!/usr/bin/perl

#
# NethServer bootstrap-console
#

use strict;
use Env;
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open_ro;
if(! $db || $db->get_value('BootstrapConsole') ne 'enabled') {
    exit 0;
}

my $tty = `/usr/bin/tty`;
my $event = shift;
my $ttyArg = '';

if($tty !~ m[^/dev/(console|tty\d)]) {
    warn('Invalid tty name: ' . $tty);
    $ttyArg = '';
} else {
    $ttyArg = $1;
}

$ENV{TERM} = 'linux';

if (system('/sbin/e-smith/bootstrap-console', $tty) != 0) {
    exit 1;
}

exit 0;
