#!/bin/bash
# Start bootstrap-console on tty1 

# initialize networks db with ethernet information
/usr/libexec/nethserver/update-networks-db

# launch bootstrap-console
TERM=linux /sbin/e-smith/bootstrap-console /dev/tty1


