#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2007 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use File::Find;

# Remove stale symlinks from /lib/modules
finddepth(sub{unlink unless -e $_}, '/lib/modules/');

opendir(BOOT, "/boot") or die("Can't open /boot directory: $!\n");

while (defined (my $file = readdir(BOOT)))
{
    next unless $file =~ /System.map-(.*)/;
    system("/sbin/depmod", "-a", "-F", "/boot/System.map-$1", "$1")
}
closedir(BOOT) or die("Can't close /boot: $!\n");

exit (0);
