#!/bin/sh
#----------------------------------------------------------------------
# copyright (C) 1999-2006 Mitel Networks Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

NOW=$(date +%Y%m%d%H%M%S)
LIST='
    /root/upgrade.log
    /root/upgrade.log.syslog
    /var/log/anaconda.log
    /var/log/anaconda.syslog'

for i in $LIST
do
    [ -e $i ] || continue

    [ -L $i ] && continue

    mv $i $i.$NOW
    ln -s $i.$NOW $i
done

