#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 2002 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::util;

my $c = esmith::ConfigDB->open_ro;
my $domain = $c->get('DomainName')
    || die("Couldn't determine domain name");
$domain = $domain->value;

# First try to run slapcat, which may fail if slapd is running
exit 0 unless
    system("/usr/sbin/slapcat", "-l", "/home/e-smith/db/ldap/$domain.ldif");

# and failing that, restart ldap, which will generate a dump file
# in the process

my $l = $c->get('ldap');
my $status = $l->prop('status') || "disabled";
die "Couldn't run slapcat, and ldap is disabled. Won't restart." .
		"No LDIF dump produced\n"
    unless ($status eq "enabled" );
esmith::util::serviceControl
       (
           NAME   => 'ldap',
           ACTION => 'restart',
	   BACKGROUND => 'false',
       ) ||
       die "Couldn't restart ldap";

exit (0);
