#!/usr/bin/perl

use strict;
use warnings;

my $lineExists = 0;
open (RD, "</etc/fstab") || die("Cannot open input file /etc/fstab: $!\n");
while (<RD>)
{
    if ( $_ =~'/var/lib/nethserver/home.*/home.*none.*defaults,bind'){
        $lineExists = 1;
    }
}
close(RD);

if (! $lineExists == 1){
    open(my $fh, '>>', '/etc/fstab') or die ("Cannot open output file /etc/fstab: $!\n");
    print $fh "/var/lib/nethserver/home\t/home\tnone\tdefaults,bind\t0 0\n";
    close $fh;
    exit system("/bin/mount /home");
}

exit 0;
