#!/usr/bin/perl -w
#----------------------------------------------------------------------
# Copyright (C) 2005 Nethesis <support@nethesis.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License or more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

use strict;
use esmith::ConfigDB;
use esmith::AccountsDB;

my $conf = esmith::ConfigDB->open_ro or die "Couldn't open ConfigDB\n";
my $accounts = esmith::AccountsDB->open_ro or die "Couldn't open AccountsDB\n";
my $expires = $conf->get_prop("passwordstrength", "PassExpires") || 'yes';

foreach my $user ($accounts->get_all_by_prop(type => 'user', PasswordSet => 'yes'))
{
    my $userName = $user->key();

    if(($expires eq 'yes') and (($user->prop("PassExpires") || 'yes') ne 'no'))
    {
        print "Setting chage for user: $userName\n";
        system("/usr/sbin/lchage",
            "-m", $conf->get_prop("passwordstrength", "MinPassAge") || "0",
            "-M", $conf->get_prop("passwordstrength", "MaxPassAge") || "180",
            "-W", $conf->get_prop("passwordstrength", "PassWarning") || "7",
            "$userName");
    }
    else
    {
        print "Unsetting chage for user: $userName\n";
        system(qw(/usr/sbin/lchage -m 0 -M 99999 -W 7), $userName);
    }
}

exit(0);

