#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2003 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------
package esmith;

use strict;
use Errno;
use esmith::util;

my $group;
my $groups;
my @groupList;

# create group "shared" if not already present
system(qw(/usr/sbin/lgroupadd -r shared)) unless getgrnam("shared");

# Create other required groups and users
system(qw(/usr/sbin/lgroupadd -g 21 -r slocate))
    unless getgrnam("slocate");
system(qw(/usr/sbin/luseradd -u 38 -s /sbin/nologin -d /etc/ntp ntp))
    unless (getpwnam("ntp"));


# create user "admin" if not already present;
if ( !getpwnam("admin") )
{
    `/usr/sbin/luseradd -c 'e-smith administrator' -d /home/e-smith -M -s /sbin/e-smith/console admin`;
    `/usr/sbin/lgroupmod -M admin shared`;
    `/usr/sbin/lgroupmod -M admin root`;
}
else
{
    #--------------------------------------------------
    # admin account already exists. Change shell, and also make sure
    # that it is in groups "root" and "shared" without disturbing any
    # other group memberships.  First get list of existing groups for
    # admin.
    #--------------------------------------------------
    
    my $cmd = "/usr/sbin/lid -n admin";
    $groups = `$cmd 2>/dev/null`; 
    if ($? != 0)
    {
	die "Failed to get supplementary group list for admin.\n";
    }
    $groups =~ s/^\s+//; #left trim
    chomp ($groups);

    @groupList = split (/\s+/, $groups);

    #--------------------------------------------------
    # Modify group list to make sure "root" and "shared"
    # are listed exactly once each.
    #--------------------------------------------------

    @groupList = grep (!/^admin$/, @groupList);
    @groupList = grep (!/^root$/, @groupList);
    @groupList = grep (!/^shared$/, @groupList);

    push @groupList, 'root', 'shared';

    #--------------------------------------------------
    # Run usermod command to update group list for admin.
    #--------------------------------------------------

    $cmd = "/usr/sbin/lusermod -c 'e-smith administrator' -d /home/e-smith -s /sbin/e-smith/console admin";
    `$cmd`;
    if ($? != 0)
    {
	die "Failed to change shell and modify supplementary group list for admin.\n";
    }
    foreach $group (@groupList)
    {
	system("/usr/sbin/lgroupmod -M admin $group") == 0
           or die "Failed adding admin user to group $group\n";
    }
}

#--------------------------------------------------
# create user "public" if not already present
#--------------------------------------------------

`/usr/sbin/lid public 2>/dev/null`;
if ($? != 0)
{
    `/usr/sbin/luseradd  -c 'e-smith guest' -d /home/e-smith -g shared -M -s /bin/false public`;
}

# delete unwanted user accounts
foreach my $user (qw(halt shutdown sync))
{
    `/usr/sbin/luserdel $user` if getpwnam($user);
}


exit (0);
