#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::NetworksDB;
use esmith::ConfigDB;

shift; # skip event name

my $argnum = @ARGV;

if ($argnum == 0) {
    # Nothing to do
    exit 0;
}

if ( ($argnum) % 2 ) {
    die("Odd numbers of parmeters");
}

my $i = 0;
while ($i < $argnum) {
    my $old = $ARGV[$i] || '';
    my $new = $ARGV[$i+1] || '';
    $i=$i+2;

    if ($old eq '' && $new eq '') {
        die("Empty parameters");
    }

    update_refs($old, $new);
}


sub update_refs {
    my $old = shift;
    my $new = shift;

    warn "[NOTICE] Rename interface $old -> $new\n";
    foreach (glob('/var/lib/nethserver/db/*')) {
        # Replace strings inside the db, except for MAC address reservation records
        system("sed -i '/MacAddress/! {s/\\b$old\\b/$new/g}' $_");
    }
}

