#!/usr/bin/perl

#
# interface-config-write -- remove ifcfg-* interface configurations
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


use esmith::NetworksDB;
use strict;

our $output_dir = $output_dir || $ENV{ESMITH_NETWORK_OUT_DIR} || "/etc/sysconfig/network-scripts";
my $idb = esmith::NetworksDB->open;
my @interfaces = $idb->interfaces;
my $update_green = 0;

foreach my $i (@interfaces) {
    my $role = $i->prop('role') || "";
    if ($role =~ /red/) {
        _adjust_red_props($i);
       $update_green = 1;
    }
}
if ($update_green) {
    _remove_green_gateway();
} 

sub _adjust_red_props() {
    my ($i) = @_;
    my $bootproto = $i->prop('bootproto') || "static";
    if ( $bootproto eq "dhcp") {
        $i->set_prop("ipaddr","");
        $i->set_prop("netmask","");
        $i->set_prop("gateway","");
        $i->set_prop("persistent_dhclient","y"); # always renew dhcp lease
        $i->set_prop("peerdns","no"); # do not overwrite /etc/resolv.conf
    } else {
        $i->set_prop("persistent_dhclient","n");
        $i->set_prop("peerdns","yes");
    }
}

sub _remove_green_gateway() {
    my @interfaces = $idb->interfaces;
    foreach my $i (@interfaces) {
        my $role = $i->prop('role') || "";
        if ($role =~ /green/) {
            $i->delete_prop('gateway');
        }
    }
}
