#!/bin/bash

#
# interface-config-write -- remove ifcfg-* interface configurations
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

source /etc/rc.d/init.d/functions

if [ "x$ESMITH_NETWORK_OUT_DIR" == "x" ]; then
    ESMITH_NETWORK_OUT_DIR=/etc/sysconfig/network-scripts
fi

interfaces=$(ls $ESMITH_NETWORK_OUT_DIR/ifcfg-* | \
            LC_ALL=C sed -e "$__sed_discard_ignored_files" \
                       -e '/\(ifcfg-lo$\|:\|ifcfg-.*-range\)/d' \
                       -e '{ s/^ifcfg-//g;s/[0-9]/ &/}' | \
            LC_ALL=C sort -k 1,1 -k 2n | \
            LC_ALL=C sed 's/ //')


for i in $interfaces; do
    rm -f $i 2>/dev/null
done

# remove all aliases
rm -f $ESMITH_NETWORK_OUT_DIR/ifcfg-*\:? 2>/dev/null
# remove all routes
rm -f $ESMITH_NETWORK_OUT_DIR/route-* 2>/dev/null

exit 0
