#!/usr/bin/perl
use esmith::NetworksDB;
use esmith::ConfigDB;

shift; # skip event name

my $argnum = @ARGV;

if ($argnum <= 1) {
    # Nothing to do
    exit 0;
}

if ( ($argnum) % 2 ) {
    die("Odd numbers of parmeters");
}

my $i = 0;
while ($i < $argnum) {
    my $old = $ARGV[$i] || '';
    my $new = $ARGV[$i+1] || '';
    $i=$i+2;

    if ($old eq '' && $new eq '') {
        die("Empty parameters");
    }

    update_refs($old, $new);
}


sub update_refs {
    my $old = shift;
    my $new = shift;

    warn "[NOTICE] Rename interface $old -> $new\n";
    foreach (glob('/var/lib/nethserver/db/*')) {
        system("sed -i 's/\\b$old\\b/$new/g' $_");
    }
}

