#!/bin/bash

#
# interface-config-write -- remove ifcfg-* interface configurations
#
# This script is part of NethServer 
#
# Copyright (C) 2012 Nethesis srl
#
#

source /etc/rc.d/init.d/functions

if [ "x$ESMITH_NETWORK_OUT_DIR" == "x" ]; then
    ESMITH_NETWORK_OUT_DIR=/etc/sysconfig/network-scripts
fi

interfaces=$(ls $ESMITH_NETWORK_OUT_DIR/ifcfg* | \
            LANG=C sed -e "$__sed_discard_ignored_files" \
                       -e '/\(ifcfg-lo$\|:\|ifcfg-.*-range\)/d' \
                       -e '/ifcfg-[A-Za-z0-9#\._-]\+$/ { s/^ifcfg-//g;s/[0-9]/ &/}' | \
            LANG=C sort -k 1,1 -k 2n | \
            LANG=C sed 's/ //')

for i in $interfaces; do
    rm -f $i 2>/dev/null
done

# remove all aliases
rm $ESMITH_NETWORK_OUT_DIR/ifcfg-*\:? 2>/dev/null

exit 0
