#!/usr/bin/perl

#
# interface-config-write -- remove ifcfg-* interface configurations
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


use esmith::NetworksDB;
use strict;

our $output_dir = $output_dir || $ENV{ESMITH_NETWORK_OUT_DIR} || "/etc/sysconfig/network-scripts";
my $idb = esmith::NetworksDB->open_ro();
my @interfaces = $idb->interfaces;

foreach my $i (@interfaces) {
    _write_config_file($i);
}

sub _write_config_file() {
    my ($i) = @_;
    my $file = sprintf "%s/ifcfg-%s", $output_dir, $i->key;
    my $out = sprintf "NAME=%s\n",  $i->key;
    my %props = $i->props;
    my $role = $props{'role'} || '';
    return unless ($role ne '');
    foreach my $prop (sort { $a cmp $b } keys %props) {
        next unless ($prop ne 'role'); # skip role
        my $val = $props{$prop};
        $val = ucfirst($val) unless ($prop ne 'type');  #first letter of type must be capitalized
        $out .= sprintf "%s=%s\n", uc($prop), $val;
    }
    open (my $fh, '>', $file);
    print $fh $out; 
    close ($fh);
}
