#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2005 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------
package esmith;

use strict;
use Errno;

my $ipparam = $ARGV[6] || "(none)";
exit 0 unless ("$ipparam" eq "diald");

use esmith::ConfigDB;

my $c = esmith::ConfigDB->open_ro or die "Could not open config db";

my $isdn = $c->get('isdn') or exit 0;

my $status = $isdn->prop('status') || 'disabled';

exit 0 unless ("$status" eq "enabled");

open(DIALD_CONTROL, ">/etc/diald/diald.ctl")
    or die "Could not open diald control socket: $!\n";

print DIALD_CONTROL "down\n";
close(DIALD_CONTROL)
    or die "Could not close diald control socket: $!\n";
