#!/bin/bash
# This script rename a ldap tree from an old domain (dc) to a new one.
# The server MUST already be configured with the new domain.
#      

old=`slapcat 2>/dev/null | head -n1 | awk -F'dc=' '{ print $2 $3 }' | sed 's/,/\./g'` # read old domain from slapcat
new=`/sbin/e-smith/config get DomainName` # read new domain from db

if [ "$old" = "$new" ]; then
   exit 0
fi

tmp="$(mktemp)"

/usr/sbin/slapcat 2>/dev/null | /sbin/e-smith/convert_ldif $old $new > $tmp
service ldap stop
find /var/lib/ldap -type f | xargs rm -f
cp /usr/share/doc/openldap-servers-`rpm -q --queryformat='%{VERSION}' openldap-servers`/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
/usr/sbin/slapadd -c < $tmp
find /var/lib/ldap -type f | xargs chown ldap:ldap 
service ldap start
