#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 2011 - Nethsis srl
#		
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from e-smith, inc.
# For details, please visit our web site at www.e-smith.com or
# call us on 1 888 ESMITH 1 (US/Canada toll free) or +1 613 564 8000
#----------------------------------------------------------------------

# This script updates organization details according to default values in ldap db entry

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::AccountsDB;
use esmith::util;
use Net::LDAP;

my $c = esmith::ConfigDB->open_ro;
my $a = esmith::AccountsDB->open_ro;

my $l = $c->get('slapd');

my $domain = $c->get('DomainName')
    || die("Couldn't determine domain name");
 $domain = $domain->value;


#------------------------------------------------------------
# Update LDAP directory entry. First read LDAP password
#------------------------------------------------------------
my $pw = esmith::util::LdapPassword();

#------------------------------------------------------------
# Update LDAP database entry.
#------------------------------------------------------------
my $base = esmith::util::ldapBase ($domain);

my $ldap = Net::LDAP->new('localhost')
    or die "$@";

$ldap->bind(
    dn => "cn=Manager,$base",
    password => $pw
);

my $phone = $l->prop('defaultPhoneNumber') || '';
my $company = $l->prop('defaultCompany') || '';
my $street = $l->prop('defaultStreet') || '';
#my $dept = $l->prop('defaultDepartment') || '';
#my $city = $l->prop('defaultCity') || '';

my @attrs;
push @attrs, (o => $company);
push @attrs, (street => $street);
push @attrs, (telephoneNumber => $phone);
my %attrs = @attrs;
my $result = $ldap->modify ($base, replace => \%attrs);
	
$result->code &&
    warn "failed to modify entry for $base: ", $result->error ;
$ldap->unbind;

exit (0);
