#!/bin/bash
# This script rename a ldap tree from an old domain (dc) to a new one.
# The server MUST already be configured with the new domain.
# Usage:
#       ldap-rename <old_domain> <new_domain> 
#      

if [ $# -lt 2 ]; then
   echo -e "Usage: ldap-rename <old_domain> <new_domain>\n\n\tExample: ldap-rename mycompany.com newcompany.net\n"
   exit 1
fi

old=$1
new=$2

tmp="$(mktemp)"

/usr/sbin/slapcat | /sbin/e-smith/convert_ldif $old $new > $tmp
service ldap stop
find /var/lib/ldap -type f | xargs rm -f
cp /usr/share/doc/openldap-servers-`rpm -q --queryformat='%{VERSION}' openldap-servers`/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
/usr/sbin/slapadd -c < $tmp
find /var/lib/ldap -type f | xargs chown ldap:ldap 
service ldap start
