#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 2002 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::util;

my $conf = esmith::ConfigDB->open;
my $domain = $conf->get('DomainName')
    || die("Couldn't determine domain name");
$domain = $domain->value;

my $ldap = $conf->get('ldap');
if($ldap and $ldap->prop('status') eq 'enabled')
{
    esmith::util::serviceControl(
	NAME => 'ldap',
	ACTION => 'stop',
	BACKGROUND => 'false')
    or die "Unable to stop ldap\n";
}

my $file = "/home/e-smith/db/ldap/$domain.ldif";
if(-e $file)
{
    unlink($file) or die "Unable to unlink $file: $!\n";
}

my $ldapdir = "/var/lib/ldap";
opendir DIR, $ldapdir;
foreach my $file (grep(!/^\./, readdir DIR))
{
    if(-f "$ldapdir/$file")
    {
	unlink("$ldapdir/$file") 
	    or warn "Unable to unlink $ldapdir/$file: $!\n";
    }
}
closedir DIR;

