#!/usr/bin/perl -w

use esmith::util;
use esmith::ConfigDB;
use File::Temp qw(tempfile);
use Net::LDAP;

my $db = esmith::ConfigDB->open_ro;
my $DomainName = $db->get("DomainName")->value;
my $passwordstrength = $db->get("passwordstrength") or die("Can't read password policy");
my $MinPassAge = $passwordstrength->prop("MinPassAge") || 0;
my $MaxPassAge = $passwordstrength->prop("MaxnPassAge") || 180;
my $ServerName = $db->get("smb")->prop("ServerName") or die("Can't get ServerName");

my $ldapSuffix =  esmith::util::ldapBase ($DomainName);
my $ldapPassword = esmith::util::LdapPassword();
my $sid = `/usr/bin/net getlocalsid 2> /dev/null | /bin/cut -d':' -f2`;
$sid =~ s/^\s+//;
$sid =~ s/\s+$//;

die("Can't read samba local sid") unless ($sid ne "");

my $ldap;
my $maxTries = 0;
while(!($ldap = Net::LDAP->new('localhost'))) { # wait for ldap, max 10 seconds
   die ("Can't connect to LDAP server") unless ($maxTries <= 10);
   sleep 1;
   $maxTries++;
}



$ldif = <<END
dn: $ldapSuffix
objectClass: top
objectClass: dcObject
objectClass: organization
o: $ServerName

dn: ou=Users,$ldapSuffix
objectClass: top
objectClass: organizationalUnit
ou: Users

dn: ou=Groups,$ldapSuffix
objectClass: top
objectClass: organizationalUnit
ou: Groups

dn: sambaDomainName=$ServerName,$ldapSuffix
sambaDomainName: $ServerName
sambaSID: $sid
objectClass: sambaDomain
sambaMinPwdLength: 5
sambaPwdHistoryLength: 0
sambaLogonToChgPwd: 0
sambaMaxPwdAge: $MaxPassAge
sambaMinPwdAge: $MinPassAge
sambaLockoutDuration: 30
sambaLockoutObservationWindow: 30
sambaLockoutThreshold: 0
sambaForceLogoff: -1
sambaRefuseMachinePwdChange: 0

dn: ou=Idmap,$ldapSuffix
objectClass: top
objectClass: organizationalUnit
ou: idmap

dn: ou=Computers,$ldapSuffix
objectClass: top
objectClass: organizationalUnit
ou: computers

dn: cn=admin,ou=Groups,$ldapSuffix
objectClass: posixGroup
objectClass: sambaGroupMapping
gidNumber: 101
cn: admin
sambaSID: $sid-512
sambaGroupType: 2
displayName: Domain Admins
description: Domain Administrators

dn: cn=shared,ou=Groups,$ldapSuffix
objectClass: posixGroup
objectClass: sambaGroupMapping
gidNumber: 500
cn: shared
sambaSID: $sid-513
sambaGroupType: 2
displayName: Domain Users
description: Domain Users 

dn: cn=nobody,ou=Groups,$ldapSuffix
objectClass: posixGroup
objectClass: sambaGroupMapping
gidNumber: 99
cn: nobody
sambaSID: $sid-514
sambaGroupType: 2
displayName: Domain Guests
description: Domain Guests

dn: cn=Domain Computers,ou=Groups,$ldapSuffix
objectClass: posixGroup
objectClass: sambaGroupMapping
gidNumber: 515
cn: Domain Computers
sambaSID: $sid-515
sambaGroupType: 2
displayName: Domain Computers
description: Domain Computers

dn: cn=Administrators,ou=Groups,$ldapSuffix
objectClass: posixGroup
objectClass: sambaGroupMapping
gidNumber: 544
cn: Administrators
sambaSID: $sid-544
sambaGroupType: 5
displayName: Administrators
description: Administrators

dn: uid=nobody,ou=Users,$ldapSuffix
uid: nobody
gecos: nobody
homeDirectory: /home/nobody
uidNumber: 99
gidNumber: 99
objectClass: posixAccount
objectClass: shadowAccount
objectClass: account
objectClass: sambaSamAccount
cn: nobody
sambaSID: $sid-501
userPassword:: e0NSWVBUfSEkMSRDdldvYUVNaSRhYVdxaVdFYzBwMGhValhudlVlYXkv

END
;

$tmp_fh = new File::Temp( UNLINK => 1 );
print $tmp_fh $ldif ;
$filename = "$tmp_fh";

# print "ldapadd -c -x -D cn=root,$ldapSuffix -w $ldapPassword -f $filename\n";

system("ldapadd", "-c", "-x", "-D", "cn=root,$ldapSuffix", "-w", "$ldapPassword", "-f", "$filename" ) == 0
   or die ("Can't load samba provision ldif");
