#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethserver.org - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


EVENT=$1
NAME=$2
CRT=$3
KEY=$4
CHAIN=$5
DST=/etc/pki/tls/

# If we exit early, clean up intermediate files:
trap "rm -f ${DST}/certs/${NAME}.crt ${DST}/private/${NAME}.key ${DST}/certs/${NAME}-chain.crt" EXIT

if [ -z $NAME ]; then
    echo "[ERROR]: invalid name for certificate"
    exit 1
fi

umask 0022
openssl x509 -in $CRT 2>/dev/null >${DST}/certs/${NAME}.crt
if [ $? -gt 0 ]; then
    echo "[ERROR]: invalid certificate '$CRT'"
    exit 1
fi

umask 0077
openssl rsa -in $KEY 2>/dev/null >${DST}/private/${NAME}.key
if [[ $? != 0 ]]; then
    openssl ec -in $KEY 2>/dev/null >${DST}/private/${NAME}.key
    if [[ $? != 0 ]]; then
        echo "[ERROR]: invalid private key '$KEY'"
        exit 1
    fi
fi

umask 0022
if [[ -n "$CHAIN" && -s "$CHAIN" ]]; then
    openssl x509 -in $CHAIN 2>/dev/null >${DST}/certs/${NAME}-chain.crt
    if [ $? -gt 0 ]; then
        echo "[ERROR]: invalid chain file '$CHAIN'"
        exit 1
    fi
fi

# Remove error cleanup procedure handler:
trap - EXIT
