#!/usr/bin/perl 

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Service;

my $errors = 0;

#
# Import distribution GPG keys into RPM database -- Refs #1597
#
foreach (qw(
    RPM-GPG-KEY-CentOS-6
    RPM-GPG-KEY-NethServer-6
)) {
    my $keyFile = '/etc/pki/rpm-gpg/' . $_;
    if ( -f $keyFile ) {
	if( system('/bin/rpm', '--import', $keyFile) != 0) {
	    warn "[WARNING] Failed to import RPM GPG key $keyFile.";
	}
    }
}

# Adjust messagebus (dbus-daemon) service. It is required by
# NetServer::Service to probe Upstart services status correctly. 
# Refs #2645
if( ! NethServer::Service->new('messagebus')->adjust()) {
    $errors ++;
    warn "[ERROR] failed to adjust messagebus service.";
}

exit($errors == 0 ? 0 : 1);
