#!/bin/bash

#
# Set /etc/pam.d/system-auth symlink to our file.
# See man (8) authconfig, man (5) system-auth-ac for details
#

if [ -r /etc/pam.d/system-auth-nh ]; then
   ln -sf /etc/pam.d/system-auth-nh /etc/pam.d/system-auth
   ln -sf /etc/pam.d/password-auth-nh /etc/pam.d/password-auth
fi