#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

event=$1
eorepo_cfg=/etc/nethserver/eorepo.conf

if [[ -r ${eorepo_cfg} ]]; then
    repositories=($(grep -v -e '^#' -e '^$' ${eorepo_cfg}))
fi

if [[ ${#repositories[@]} -gt 0 ]]; then
    echo "[NOTICE] eorepo ${repositories[*]}"
    /sbin/e-smith/eorepo ${repositories[*]}
    yum --setopt=exit_on_lock=1 clean all && rm -rf /var/cache/yum/*
fi

exit 0