#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::NetworksDB;
use strict;

qx(/sbin/service network stop);

our $output_dir = $output_dir || $ENV{ESMITH_NETWORK_OUT_DIR} || "/etc/sysconfig/network-scripts";

my %current = {};
# Query the currently active interfaces:
foreach (split(/\n/, `ip -o link`)) {
   my ($id, $name, $details) = split(/:/, $_);
   next if ($name =~ "lo");

   # Ensure all ethernets are down:
   my $output = `ip link set $name down 2>&1`;
   if ( $? != 0 ) {
       warn "Could not bring down " . $name . ": " . $output . "\n";
   }
}

exit 0;
