#!/bin/bash
if [ "x$ESMITH_NETWORK_OUT_DIR" == "x" ]; then
    ESMITH_NETWORK_OUT_DIR=/etc/sysconfig/network-scripts
fi
interfaces=$(ls $ESMITH_NETWORK_OUT_DIR/ifcfg* | \
            LANG=C sed -e "$__sed_discard_ignored_files" \
                       -e '/\(ifcfg-lo$\|:\|ifcfg-.*-range\)/d' \
                       -e '/ifcfg-[A-Za-z0-9#\._-]\+$/ { s/^ifcfg-//g;s/[0-9]/ &/}' | \
            LANG=C sort -k 1,1 -k 2n | \
            LANG=C sed 's/ //')

for i in $interfaces; do
    rm -f $i
done

exit 0
