#!/bin/bash

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

if ! [ $# -ge 3 ]; then
   echo "[ERROR] Not enough arguments."
   exit 2
fi

EVENT=$1
USER=$2
FILE=$3

if ! [ -f "${FILE}" ]; then
    echo "[ERROR] Password file not found"
    exit 1
fi

PASSWORD=`cat $FILE`
echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin $USER

if [ "$USER" == "admin" ]; then
    other="root"
elif [ "$USER" == "root" ]; then
    other="admin"
else
    other=""
fi

if [ -n "${other}" ] && /usr/bin/getent passwd "${other}" &>/dev/null; then
    AdminIsNotRoot=$(/sbin/e-smith/config get AdminIsNotRoot)
    if [ "$AdminIsNotRoot" != "enabled" ]; then 
	# Synchronize password with "other" account (see #2492.9)
        echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin "${other}"
    fi
fi

