#!/usr/bin/perl

my $excludes = 'swap proc sysfs devpts tmpfs';

my @lines = ();
open (RD, "</etc/fstab") || die("Cannot open input file /etc/fstab: $!\n");
while (<RD>)
{
    chop;
    if ($_ =~ /^#/) { # skip comments
        next;
    }
    my @line =  split(/\s+/, $_);
    # remount filesystem if not in the exclude list 
    $errors += system("/bin/mount -o remount ".$line[0]) unless  ($excludes =~ $line[2]) ;
}
close(RD);

exit ($errors>0?1:0);
