#!/bin/bash

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING
#

rm -f /etc/udev/rules.d/70-persistent-net.rules
/sbin/udevadm trigger --subsystem-match=net --verbose

# prevent race conditions with update-networks-db
echo "[INFO] start waiting for udev..." $(date +%T.%N) 1>&2
/sbin/udevadm settle --timeout=30
echo "[INFO] done waiting for udev!" $(date +%T.%N) 1>&2

