#!/bin/sh

#----------------------------------------------------------------------
# copyright (C) 2001-2005 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

#------------------------------------------------------------
# Set $GatewayIP in configuration db, for use by templates
#------------------------------------------------------------
# my $event = $1

# These params all come via pppd, via ip-up.local
# interface_name = $2
# tty-device = $3
# speed = $4
# local_ip = $5
# remote_ip = $6
# ipparam = $7

if [ "$7" = "diald" ]
then
    exec /sbin/e-smith/config set GatewayIP "$6"
fi
exit 0
