#!/bin/bash

if [ $# -ge 3 ]; then
   EVENT=$1
   USER=$2
   FILE=$3
   echo "Change password for user $USER from $FILE"
   if [ -f $FILE ]; then
     PASSWORD=`cat $FILE`
     echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin $USER
     /sbin/e-smith/db accounts setprop $USER __state active
   else
     echo "Password file not found"
     exit 1
   fi
else
   echo "Not enough arguments"
   exit 1
fi
