#!/usr/bin/python

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
sys.path.append('/usr/lib/yum-plugins')

import nethserver_events

events = nethserver_events.filter_update_events(nethserver_events.read_package_list())

events.append('firewall-adjust')
events.append('runlevel-adjust')

success = nethserver_events.run_events(events)

sys.exit(0 if success else 1)
