#!/bin/bash

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

grep -q NethServer /etc/system-release
if [ $? -eq 0 ]; then
   exit 0
fi

/bin/sed -i 's/CentOS/NethServer/' /etc/issue 2>/dev/null
/bin/sed -i 's/^hiddenmenu/#hiddenmenu/' /boot/grub/grub.conf 2>/dev/null
/bin/sed -i 's/CentOS/NethServer/' /etc/system-release 2>/dev/null
# execute dracut in background
/usr/bin/nohup /sbin/new-kernel-pkg --package kernel --mkinitrd --dracut --depmod --update $(uname -r) & 2>/dev/null

