#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 2001-2006 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use English;

exit 1 unless (defined $ARGV[0] && defined $ARGV[1]);

my $userName = $ARGV[0];
my $password = $ARGV[1];

system("/usr/sbin/lusermod", "-P", "$password", "$userName") == 0
   or die "Error running /usr/sbin/lusermod command to update password for  account $userName";

system("echo -ne \"$password\n$password\n\" | /usr/bin/smbpasswd -s $userName") == 0
   or die "Error running /usr/bin/smbpasswd command to update password for  account $userName";
exit 0;
