#!/usr/bin/perl -w
#----------------------------------------------------------------------
# Copyright (C) 2005 Nethesis <support@nethesis.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
# Technical support for this program is available from Mitel Networks
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::AccountsDB;

my $conf = esmith::ConfigDB->open_ro;
my $accounts = esmith::AccountsDB->open;

my $event = $ARGV [0];
my $userName = $ARGV [1];

#------------------------------------------------------------
# Chage the Unix account
#------------------------------------------------------------

die "username argument missing" unless defined ($userName);

my $expires = $conf->get_prop("passwordstrength", "PassExpires") || 'yes';

if ($expires eq 'yes')
{
    system("/usr/bin/chage",
        "-m", $conf->get_prop("passwordstrength", "MinPassAge") || "0",
        "-M", $conf->get_prop("passwordstrength", "MaxPassAge") ||  "180",
        "-W", $conf->get_prop("passwordstrength", "PassWarning") || "7",
        "$userName");
}

exit (0);
