#!/usr/bin/perl -w

use strict;
use esmith::AccountsDB;

my $accountdb = esmith::AccountsDB->open() or
    die "Unable to open accounts db";

my ($event, $acctName) = @ARGV;

$accountdb->remove_user_from_groups($acctName, $accountdb->user_group_list($acctName));


