#!/usr/bin/perl -w

use strict;
use Errno;
use esmith::AccountsDB;
use esmith::ConfigDB;
use IO::File;
use English;

my $a = esmith::AccountsDB->open or die "Could not open accounts db";
my $conf = esmith::ConfigDB->open or die "Could not open configuration db";

my $event = $ARGV [0];
my $user = $ARGV[1] || die "No user specified";

unlock_user($user);

exit 0;

sub unlock_user
{
    my ($userName) = @_;
    #------------------------------------------------------------
    # Lock the user account in all authentication databases
    #------------------------------------------------------------

    my $u = $a->get($userName) or die "No account record for user $userName";

    system("/usr/sbin/lusermod", "-U", $userName) == 0
        or die "Error running /usr/sbin/lusermod command to lock account $userName";
    system("/usr/bin/smbpasswd", "-e", $userName) == 0
        or die "Error running /usr/bin/smbpasswd command to lock account $userName";
    $u->set_prop('Locked', 'no');

}
