#!/usr/bin/python

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import os
import sys

out = ''

try:
    out = os.popen('/usr/libexec/nethserver/eth-unmapped').read()
except:	
    pass

if(not out):
    exit(1)

unmapped_interfaces = json.loads(out, 'UTF-8')

if(len(unmapped_interfaces) > 0):
    gettext.textdomain('nethserver-base')
    msg = {
        "action": {
            "label": gettext.ngettext('Assign role to network interface', 'Assign roles to network interfaces', len(unmapped_interfaces)).format(len(unmapped_interfaces)),
            "url": '/NetworkAdapter?renameInterface'
        },
        "icon": "bolt",
        "text": gettext.ngettext('A role must be assigned to a new network card', 'There are {0} roles to be assigned to network cards'  , len(unmapped_interfaces)).format(len(unmapped_interfaces))
    }
    json.dump(msg, sys.stdout)
	    
