#!/usr/bin/python

#
# Copyright (C) 2016 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import os
import sys

out = ''

try:
    out = os.popen('/sbin/e-smith/db networks showjson').read()
except:	
    pass

if(not out):
    exit(1)

interfaces = json.loads(out, 'UTF-8')
warn = 0

for i in interfaces:
    try:
        if i['props']['role'] == 'green':
            if i['props']['bootproto'] == 'dhcp':
                warn = warn + 1
    except:
        continue

if( warn > 0):
    gettext.textdomain('nethserver-base')
    msg = {
        "action": {
            "label": gettext.gettext('One or more green interfaces use DHCP'),
            "url": '/NetworkAdapter'
        },
        "icon": "bolt",
        "text": gettext.gettext('Using DHCP on green interfaces leads to unexpected behavior. Please, change the interface to static if possible')
    }
    json.dump(msg, sys.stdout)
	    
