#!/usr/bin/perl -w
package esmith;

use esmith::ConfigDB;

=head2 validate_account_length ACCOUNTNAME

returns 'OK' if the account name is shorter than the maximum account name length
returns 'ACCOUNT_TOO_LONG' otherwise

=cut

my $groupName = shift || die("Missing group name argument");
my $db = esmith::ConfigDB->open_ro() or die("Could not open ConfigDB");
    
my $maxGroupNameLength = ($db->get('maxGroupNameLength')
   ? $db->get('maxGroupNameLength')->prop('type')
   : "") || 32;

if ( length $groupName > $maxGroupNameLength ) {
    print "Max length is: $maxGroupNameLength\n"; 
    exit 1 
}

exit 0;

