#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

H=$(echo "$1" | cut -d. -f1)

# NetBIOS length limit for hostname H
if (( ${#H} > 15 || ${#H} == 0 )); then
    exit 3
fi

# Check it is composed by "letters, digits, hyphens, and periods":
if [[ -n "$(tr -d '[:alnum:].-' <<< ${H})" ]]; then
    exit 4
fi

exit 0
