#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use JSON qw(decode_json);
use esmith::NetworksDB;

my $r = decode_json($ARGV[0]);
my %h = %{$r};

# Initialize missing parameters as empty strings:
foreach (qw(device hwaddr role bootproto ipaddr netmask gateway)) {
    if( ! defined $h{$_} ) {
	$h{$_} = '';
    }
}


#
# 1. Only red interfaces can use DHCP
#
if($h{'bootproto'} eq 'dhcp' && $h{'role'} ne 'red') {
    print "only_red_dhcp\n";
    exit 3;
}

#
# 2. There must be a green interface
#
if($h{'role'} ne 'green') {

    my $ndb = esmith::NetworksDB->open_ro() || die("Could not open NetworksDB");
    
    if( ! grep { $_->key() eq $h{'device'} ? () : $_ } $ndb->green()) {
	print "one_green_at_least\n";
	exit 4;
    }
}


