#!/usr/bin/perl
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
use strict;
use IO::Handle;

my $port_number = shift || die('Missing port number argument');
my $server_name = shift || die('Missing server name argument');

=head1 validate-remote-port

Arguments: <port_number> <po <server_name>

=cut

use esmith::util::network;

if( ! esmith::util::network::isValidPort($port_number) ) {
    # Invalid port number argument
    exit 3;
}

if( ! (esmith::util::network::isValidHostname($server_name)) ) {
    # Invalid host address
    exit 4;
}

my $output = qx(/usr/bin/nc -z -v $server_name $port_number 2>&1);

if($? != 0) {
    my $reason = [split(/:\s+/, $output, 3)]->[-1];
    print $reason;
    exit 1;
}

exit 0;
