#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 - Nethesis srl
# 

use strict;
use esmith::ConfigDB;
use Crypt::Cracklib;


my $objectType = shift;
my $password = shift;
my $reason;

if( ! defined $objectType ) {
    die "Missing objectType argument";
}

if( ! defined $password ) {
    die "Missing password argument";
}

my $configDb = esmith::ConfigDB->open_ro();
my $strength = $configDb->get_prop('passwordstrength', $objectType);

if ( ! defined $strength ) {
    # skip to end..

} elsif( length($password) < 7 ) {
    # too_short
    exit 3;

} elsif( $strength eq 'none' ) {
    exit 0;

} elsif( $strength eq 'strong') {
    if (not $password =~ /\d/ 
	&& $password =~ /[A-Z]/
	&& $password =~ /[a-z]/
	&& $password =~ /\W|_/) {
	# missing char_classes
	exit 4;
    }

    $reason = Crypt::Cracklib::fascist_check($password);
    if($reason ne 'ok') {
	print $reason . "\n";
	exit 5;
    }

    exit 0;   
} 

die "Invalid password strength for object " . $objectType;

