#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

privkey=$1
tlspolicy=$2

openssl ec -in "${privkey}" -noout &>/dev/null
if [[ $? == 0 ]]; then
    if [[ -z ${tlspolicy} ]] || (( ${tlspolicy} >= 20180621 )); then
        exit 0
    else
        exit 3
    fi
fi

exit 0
