#!/usr/bin/perl -w
package esmith;

use esmith::AccountsDB;


=head2 validate_acctName_conflict

Returns 'OK' if the account name doesn't yet exist.  Returns a localised error
otherwise.

=cut

my $acctName = shift || die('Missing account name argument');
my $accountdb = esmith::AccountsDB->open_ro() || die('Could not open AccountsDB');

my $account = $accountdb->get($acctName);
my $type;

if (defined $account)
{
    $type = $account->prop('type');
}
elsif (defined getpwnam($acctName) || defined getgrnam($acctName))
{
    $type = "system";
}
else
{
    exit 0;
}

print "A $type account with the same name already exists\n";
exit 3;
