#!/usr/bin/perl -w
package esmith;

use esmith::ConfigDB;

=head2 validate_account_length ACCOUNTNAME

returns 'OK' if the account name is shorter than the maximum account name length
returns 'ACCOUNT_TOO_LONG' otherwise

=cut

my $acctName = shift;
exit 1 unless ($acctName ne "");

my $db = esmith::ConfigDB->open_ro() or exit 1;
    

my $maxAcctNameLength = ($db->get('maxAcctNameLength')
   ? $db->get('maxAcctNameLength')->prop('type')
   : "") || 32;

if ( length $acctName > $maxAcctNameLength ) {
    print "'$acctName' is too long. Max length is: $maxAcctNameLength\n"; 
    exit 1 
} else {
    exit 0;
}
