#!/usr/bin/perl

use strict;

my $port_number = shift;
my $port_type = shift;
my $server_name = shift;

=head1 validate-remote-port

Arguments: <port_number> <port_type> <server_name>

=cut

use esmith::util::network;

if( ! $port_type =~ m/^(udp|tcp)$/ ) {
    warn "Invalid port type argument\n";
    exit 1;
}

if( ! esmith::util::network::isValidPort($port_number) ) {
    warn "Invalid port number argument\n";
    exit 1;
}

if( ! (esmith::util::network::isValidHostname($server_name)) ) {
    warn "Invalid host address\n";
    exit 1;
}

my $port_type_flag = $port_type eq 'udp' ? '-u' : '';

open(my $nc, '-|', "/usr/bin/nc -z $port_type_flag -v $server_name $port_number 2>&1");
my $output = <$nc>;
chomp($output);
print [split(/:\s+/, $output, 3)]->[-1] . "\n";
close($nc);

exit($? == 0 ? 0 : 1);
